name: torch_env 
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - torch  
  - pandas   
  - scipy   
  - numpy      
  - biopython
  - scikit-learn
  - seaborn
  - matplotlib
